version: '3.8'

services:
  base:
    build: ./base
    image: custom-postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build: ./Application-test
    image: flask-app
    container_name: flask_container
    ports:
      - "5000:5000"
    depends_on:
      - base
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
